Wait when stopping supervisor
Fixes a problem where we issue a start before supervisor has cleaned up
child pids (Ubuntu only).

Trello: https://trello.com/c/5rOxYcY5

diff --git a/tools/scripts/ansible-tower b/tools/scripts/ansible-tower
--- a/tools/scripts/ansible-tower
+++ b/tools/scripts/ansible-tower
@@ -25,11 +25,16 @@ fi
 
 service_action() {
     for svc in ${SERVICES[@]}; do
-	service ${svc} $1
-	this_return=$?
-	if [ $this_return -gt $worst_return ]; then
-	    worst_return=$this_return
-	fi
+        service ${svc} $1
+        this_return=$?
+        if [ $this_return -gt $worst_return ]; then
+            worst_return=$this_return
+        fi
+        # Allow supervisor time to cleanup child pids (ubuntu only)
+        if [[ ${svc} == supervisor* && ${1} == stop && -e /etc/debian_version ]]; then
+            echo "Waiting to allow supervisor time to cleanup ..."
+            sleep 5
+        fi
     done
 }
 
